root: /LW-blog/

inject:
  head:
    - '<link rel="stylesheet" href="/LW-blog/css/custom.css">'
    - '<link rel="stylesheet" href="/LW-blog/music/player.css">'
  bottom:
    - '<script src="/LW-blog/music/player.js" defer></script>'
